/*
 *  UCF COP3330 Summer 2021 Assignment 4 Solution
 *  Copyright 2021 Michael Hickey
 */

@startuml
'https://plantuml.com/class-diagram

class App {
    + main()
    + start()
}

class AppController {
    - displayListTitle : TextField
    - displayItemTitle : TextField
    - displayItemDescription : TextField
    - displayDueDate : TextField

    + viewListClicked()
    + editListClicked()
    + deleteListClicked()
    + newListClicked()
    + checkListMarked()
    + saveListClicked()
    + newTaskClicked()
    + editTaskClicked()
    + saveTaskClicked()
    + deleteTaskClicked()
    + checkTaskMarked()
    + completed()
}

javafx.Application <|-- App
App - AppController

@enduml